### ISSUE TITLE
Setting up config file | Test Rico's WMT16 EN-DE  

### ISSUE THREAD

**Issue by mehmedes** [emjotde/amunmt#25]
If I wanted to test Rico's model on a non-gpu instance would this be the setup to use:

# Paths are relative to config file location
relative-paths: yes

# performance settings
beam-size: 12
devices: [0]
normalize: yes
gpu-threads: 0

# scorer configuration
scorers:
  F0:
    path: model.npz
    type: Nematus

# scorer weights
weights:
  F0: 1.0

# vocabularies
source-vocab: vocab.en.json
target-vocab: vocab.de.json

bpe: ende.bpe
debpe: true

cpu-threads: 8
gpu-threads: 0
devices: [1, 0]

When running ./bin/amun -c config.yml <<< "This is a test ." , I end up with Segmentation fault (core dumped) .

Would it be possible to run all four models model-ens{1,2,3,4}?

**Comment by emjotde** [comment]
This works for me (BTW, does this mean you were able to compile?):

```
allow-unk: false
batch-size: 1
beam-size: 12
bpe:
  - deen.bpe
bunch-size: 1
cpu-threads: 8
devices: [0]
gpu-threads: 0
n-best: false
no-debpe: false
normalize: false
relative-paths: true
return-alignment: false
scorers:
  F0:
    path: model.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - vocab.de.json
target-vocab: vocab.en.json
weights:
  F0: 1
wipo: false
```

**Comment by emjotde** [comment]
And for four models:

```
allow-unk: false
batch-size: 1
beam-size: 12
bpe:
  - deen.bpe
bunch-size: 1
cpu-threads: 8
devices: [0]
gpu-threads: 0
n-best: false
no-debpe: false
normalize: false
relative-paths: true
return-alignment: false
scorers:
  F0:
    path: model-ens1.npz
    type: Nematus
  F1:
    path: model-ens2.npz
    type: Nematus
  F2:
    path: model-ens3.npz
    type: Nematus
  F3:
    path: model-ens4.npz
    type: Nematus
show-weights: false
softmax-filter:
  []
source-vocab:
  - vocab.de.json
target-vocab: vocab.en.json
weights:
  F0: 1
  F1: 1
  F2: 1
  F3: 1
wipo: false
```
